/**
 * Creature statistics by level, for approximate level scaling.
 *
 * NOT rules as written. The GM Core creature-building tables are printed text
 * and are not present in any bundled data, so this table is fitted: it is the
 * median of each statistic across 6368 bundled creatures, excluding legacy
 * reprints superseded by a remaster entry.
 * 
 * The fit is close to the printed "moderate" column where that can be checked
 * by hand (level 1 HP 20, level 2 HP 30, level 5 HP 75), which is why it is
 * usable, but it is a description of what Paizo published rather than of what
 * the tables prescribe. Scaling built on it must be labelled an approximation
 * in the interface, distinct from elite and weak.
 * 
 * To replace it with transcribed GM Core values, overwrite the rows below and
 * set `source` to a citation; nothing else in the engine needs to change.
 * Fitted from data built at upstream commit 8c8a688a3225ac8147c1cb24e4c570bc22db954b.
 *
 * GENERATED by `npm run build:tables`. Do not edit by hand.
 */

export const SCALING_SOURCE = 'fitted';

export const CREATURE_STATS_BY_LEVEL = {
  "0": {
    "n": 139,
    "ac": 15,
    "hp": 15,
    "perception": 6,
    "attack": 7,
    "save": 6,
    "spellDc": 16
  },
  "1": {
    "n": 499,
    "ac": 16,
    "hp": 20,
    "perception": 7,
    "attack": 8,
    "save": 7,
    "spellDc": 17
  },
  "2": {
    "n": 509,
    "ac": 17,
    "hp": 30,
    "perception": 8,
    "attack": 10,
    "save": 8,
    "spellDc": 18
  },
  "3": {
    "n": 519,
    "ac": 18,
    "hp": 45,
    "perception": 9,
    "attack": 11,
    "save": 9,
    "spellDc": 20
  },
  "4": {
    "n": 466,
    "ac": 21,
    "hp": 60,
    "perception": 11,
    "attack": 13,
    "save": 11,
    "spellDc": 21
  },
  "5": {
    "n": 452,
    "ac": 21,
    "hp": 75,
    "perception": 12,
    "attack": 15,
    "save": 12,
    "spellDc": 22
  },
  "6": {
    "n": 392,
    "ac": 23,
    "hp": 95,
    "perception": 14,
    "attack": 17,
    "save": 14,
    "spellDc": 24
  },
  "7": {
    "n": 402,
    "ac": 25,
    "hp": 115,
    "perception": 15,
    "attack": 18,
    "save": 15,
    "spellDc": 25
  },
  "8": {
    "n": 357,
    "ac": 26,
    "hp": 135,
    "perception": 16,
    "attack": 20,
    "save": 16,
    "spellDc": 26
  },
  "9": {
    "n": 314,
    "ac": 27,
    "hp": 155,
    "perception": 18,
    "attack": 21,
    "save": 18,
    "spellDc": 28
  },
  "10": {
    "n": 265,
    "ac": 29,
    "hp": 175,
    "perception": 19,
    "attack": 23,
    "save": 19,
    "spellDc": 29
  },
  "11": {
    "n": 246,
    "ac": 30,
    "hp": 195,
    "perception": 21,
    "attack": 24,
    "save": 21,
    "spellDc": 30
  },
  "12": {
    "n": 192,
    "ac": 32,
    "hp": 215,
    "perception": 22,
    "attack": 26,
    "save": 22,
    "spellDc": 32
  },
  "13": {
    "n": 229,
    "ac": 33,
    "hp": 235,
    "perception": 23,
    "attack": 27,
    "save": 23,
    "spellDc": 33
  },
  "14": {
    "n": 187,
    "ac": 36,
    "hp": 255,
    "perception": 25,
    "attack": 29,
    "save": 25,
    "spellDc": 34
  },
  "15": {
    "n": 175,
    "ac": 37,
    "hp": 275,
    "perception": 27,
    "attack": 30,
    "save": 26,
    "spellDc": 36
  },
  "16": {
    "n": 152,
    "ac": 39,
    "hp": 295,
    "perception": 28,
    "attack": 32,
    "save": 28,
    "spellDc": 37
  },
  "17": {
    "n": 139,
    "ac": 40,
    "hp": 315,
    "perception": 30,
    "attack": 33,
    "save": 29,
    "spellDc": 38
  },
  "18": {
    "n": 161,
    "ac": 42,
    "hp": 335,
    "perception": 32,
    "attack": 35,
    "save": 30,
    "spellDc": 40
  },
  "19": {
    "n": 99,
    "ac": 43,
    "hp": 360,
    "perception": 33,
    "attack": 36,
    "save": 32,
    "spellDc": 41
  },
  "20": {
    "n": 114,
    "ac": 45,
    "hp": 380,
    "perception": 36,
    "attack": 38,
    "save": 34,
    "spellDc": 42
  },
  "21": {
    "n": 52,
    "ac": 46,
    "hp": 400,
    "perception": 38,
    "attack": 39,
    "save": 35,
    "spellDc": 44
  },
  "22": {
    "n": 38,
    "ac": 48,
    "hp": 450,
    "perception": 39,
    "attack": 41,
    "save": 36,
    "spellDc": 45
  },
  "23": {
    "n": 31,
    "ac": 49,
    "hp": 480,
    "perception": 40,
    "attack": 42,
    "save": 39,
    "spellDc": 46
  },
  "24": {
    "n": 11,
    "ac": 51,
    "hp": 525,
    "perception": 42,
    "attack": 44,
    "save": 39,
    "spellDc": 48
  },
  "25": {
    "n": 5,
    "ac": 52,
    "hp": 550,
    "perception": 43,
    "attack": 45,
    "save": 41,
    "spellDc": 49
  },
  "-1": {
    "n": 223,
    "ac": 15,
    "hp": 8,
    "perception": 5,
    "attack": 6,
    "save": 4,
    "spellDc": 15
  }
};
