/**
 * Level-based DCs and DC adjustments.
 *
 * Source: GM Core pg. 53, via the pinned pf2e GM Screen journal.
 * Upstream commit 8c8a688a3225ac8147c1cb24e4c570bc22db954b.
 *
 * GENERATED by `npm run build:tables`. Do not edit by hand.
 */

export const DC_BY_LEVEL = {
  "0": 14,
  "1": 15,
  "2": 16,
  "3": 18,
  "4": 19,
  "5": 20,
  "6": 22,
  "7": 23,
  "8": 24,
  "9": 26,
  "10": 27,
  "11": 28,
  "12": 30,
  "13": 31,
  "14": 32,
  "15": 34,
  "16": 35,
  "17": 36,
  "18": 38,
  "19": 39,
  "20": 40,
  "21": 42,
  "22": 44,
  "23": 46,
  "24": 48,
  "25": 50,
  "-1": 13
};

export const DC_BY_SPELL_RANK = {
  "1": 15,
  "2": 18,
  "3": 20,
  "4": 23,
  "5": 26,
  "6": 28,
  "7": 31,
  "8": 34,
  "9": 36,
  "10": 39
};

/** Difficulty adjustments, e.g. `hard` -> +2. */
export const DC_ADJUSTMENT = {
  "incredibly easy": -10,
  "very easy": -5,
  "easy": -2,
  "hard": 2,
  "very hard": 5,
  "incredibly hard": 10
};

/** The rarity each adjustment is tied to, e.g. `rare` -> +5. */
export const DC_BY_RARITY = {
  "uncommon": 2,
  "rare": 5,
  "unique": 10,
  "common": 0
};
