/**
 * Encounter budget by difficulty, for a party of four.
 *
 * Source: GM Core pg. 75, via the pinned pf2e GM Screen journal.
 * Creature costs below are the companion table on the same page; they are not
 * in the bundled journal and are transcribed from the printed table.
 * Upstream commit 8c8a688a3225ac8147c1cb24e4c570bc22db954b.
 *
 * GENERATED by `npm run build:tables`. Do not edit by hand.
 */

export const ENCOUNTER_BUDGET = {
  "trivial": {
    "xp": 40,
    "perCharacter": 10
  },
  "low": {
    "xp": 60,
    "perCharacter": 20
  },
  "moderate": {
    "xp": 80,
    "perCharacter": 20
  },
  "severe": {
    "xp": 120,
    "perCharacter": 30
  },
  "extreme": {
    "xp": 160,
    "perCharacter": 40
  }
};

/**
 * XP a creature costs against the party level, by level difference.
 * GM Core pg. 75. Outside -4..+4 the table simply does not extend, and the
 * builder says so rather than extrapolating.
 */
export const CREATURE_XP_BY_LEVEL_DIFFERENCE = {
  "0": 40,
  "1": 60,
  "2": 80,
  "3": 120,
  "4": 160,
  "-4": 10,
  "-3": 15,
  "-2": 20,
  "-1": 30
};
