#!/usr/bin/env node
/**
 * `npm run build:tables`
 *
 * Emits the rules engine's lookup tables into `src/rules/tables/` as checked-in
 * ES modules.
 *
 * Checked in rather than generated into `data/` for two reasons: the rules
 * engine must run in the browser with no data build behind it, and the test
 * suite must not depend on `npm run build:data` having been run.
 *
 * Two sources, and the distinction matters:
 *
 *   - The GM Screen journal in the pinned foundryvtt/pf2e checkout. These are
 *     transcriptions of printed GM Core tables and carry a page citation.
 *     Authoritative.
 *   - The normalized bestiary in `data/`. Used only for the level-scaling
 *     table, which has no printed equivalent we can bundle. Fitted, and
 *     labelled as such everywhere it surfaces.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve as resolvePath } from 'node:path';

import { ensureUpstream, LOCK, PROJECT_ROOT } from '../build-data/upstream.js';
import { buildUuidIndex } from '../build-data/uuid-index.js';
import { loadGlossary } from '../build-data/glossary.js';
import { createMarkupResolver } from '../build-data/markup.js';

const OUT_DIR = resolvePath(PROJECT_ROOT, 'src/rules/tables');

/** Minimal `<table>` reader: returns each table as an array of cell-text rows. */
function parseTables(html) {
  const tables = [];
  for (const [, body] of html.matchAll(/<table[^>]*>([\s\S]*?)<\/table>/g)) {
    const rows = [];
    for (const [, tr] of body.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/g)) {
      const cells = [...tr.matchAll(/<t[hd][^>]*>([\s\S]*?)<\/t[hd]>/g)]
        .map(([, c]) => c.replace(/<[^>]+>/g, '').replace(/&[a-z]+;/g, ' ').trim());
      rows.push(cells);
    }
    tables.push(rows);
  }
  return tables;
}

function gmScreenPages(upstream) {
  const file = resolvePath(upstream, 'packs/pf2e/journals/gm-screen.json');
  const journal = JSON.parse(readFileSync(file, 'utf8'));
  const pages = new Map();
  for (const page of journal.pages ?? []) pages.set(page.name, page.text?.content ?? '');
  return pages;
}

/** "Section: Running the Game Pathfinder GM Core pg. 53" -> "GM Core pg. 53". */
function citationOf(html) {
  const m = /Pathfinder\s+(GM Core|Player Core|Monster Core)\s*pg\.\s*(\d+)/.exec(
    html.replace(/<[^>]+>/g, ' '),
  );
  return m ? `${m[1]} pg. ${m[2]}` : null;
}

function header(title, provenance) {
  return `/**\n * ${title}\n *\n${provenance.map((l) => ` * ${l}`).join('\n')}\n *\n * GENERATED by \`npm run build:tables\`. Do not edit by hand.\n */\n`;
}

const js = (v) => JSON.stringify(v, null, 2);

// ---------------------------------------------------------------- DCs by level

function buildDcTable(pages) {
  const html = pages.get('DCs by Level');
  const [levelTable, spellTable] = parseTables(html);

  /** The printed table is two level/DC column pairs side by side. */
  const byLevel = {};
  for (const row of levelTable.slice(1)) {
    const pairs = [[row[0], row[1]], [row[3], row[4]]];
    for (const [lvl, dc] of pairs) {
      if (lvl === undefined || !/^-?\d+$/.test(lvl)) continue;
      byLevel[Number(lvl)] = Number(dc);
    }
  }
  // The bundled table starts at level 0. Level -1 is DC 13 in the printed
  // table, and Recall Knowledge against level -1 creatures is routine, so it
  // is added here rather than left to a clamp.
  byLevel[-1] = 13;

  const bySpellRank = {};
  for (const row of spellTable.slice(1)) {
    const m = /^(\d+)/.exec(row[0] ?? '');
    if (m) bySpellRank[Number(m[1])] = Number(row[1]);
  }

  const adjHtml = pages.get('DC Adjustments');
  const [adjTable] = parseTables(adjHtml);
  const byDifficulty = {};
  const byRarity = {};
  for (const row of adjTable.slice(1)) {
    const [label, adjustment, rarity] = row;
    if (!label || !adjustment) continue;
    const value = Number(adjustment.replace(/[–−]/g, '-').replace(/[^\d-]/g, ''));
    byDifficulty[label.toLowerCase()] = value;
    if (rarity && rarity !== '—' && rarity !== '-') byRarity[rarity.toLowerCase()] = value;
  }
  byRarity.common = 0;

  return header('Level-based DCs and DC adjustments.', [
    `Source: ${citationOf(html) ?? 'GM Core'}, via the pinned pf2e GM Screen journal.`,
    `Upstream commit ${LOCK.commit}.`,
  ]) + `
export const DC_BY_LEVEL = ${js(byLevel)};

export const DC_BY_SPELL_RANK = ${js(bySpellRank)};

/** Difficulty adjustments, e.g. \`hard\` -> +2. */
export const DC_ADJUSTMENT = ${js(byDifficulty)};

/** The rarity each adjustment is tied to, e.g. \`rare\` -> +5. */
export const DC_BY_RARITY = ${js(byRarity)};
`;
}

// -------------------------------------------------------- Recall Knowledge

function buildRecallTable(pages) {
  const html = pages.get('Creature Identification');
  const [table] = parseTables(html);
  const byTrait = {};
  for (const row of table.slice(1)) {
    const [trait, skills] = row;
    if (!trait || !skills) continue;
    byTrait[trait.toLowerCase()] = skills.split(',').map((s) => s.trim().toLowerCase());
  }
  return header('Creature identification: which skill recalls which creature.', [
    `Source: ${citationOf(html) ?? 'GM Core'}, via the pinned pf2e GM Screen journal.`,
    'A creature with no listed trait falls back to Lore, which is always allowed',
    'at the GM’s discretion (GM Core, Recall Knowledge).',
    `Upstream commit ${LOCK.commit}.`,
  ]) + `
export const RK_SKILL_BY_TRAIT = ${js(byTrait)};
`;
}

// ------------------------------------------------------------ Encounter budget

function buildEncounterTable(pages) {
  const html = pages.get('Encounter Budget');
  const [table] = parseTables(html);
  const budget = {};
  for (const row of table.slice(1)) {
    const [difficulty, xp, adjustment] = row;
    if (!difficulty || !xp) continue;
    budget[difficulty.toLowerCase()] = {
      xp: Number(String(xp).replace(/[^\d]/g, '')),
      perCharacter: Number(String(adjustment).replace(/[^\d]/g, '')),
    };
  }
  return header('Encounter budget by difficulty, for a party of four.', [
    `Source: ${citationOf(html) ?? 'GM Core'}, via the pinned pf2e GM Screen journal.`,
    'Creature costs below are the companion table on the same page; they are not',
    'in the bundled journal and are transcribed from the printed table.',
    `Upstream commit ${LOCK.commit}.`,
  ]) + `
export const ENCOUNTER_BUDGET = ${js(budget)};

/**
 * XP a creature costs against the party level, by level difference.
 * GM Core pg. 75. Outside -4..+4 the table simply does not extend, and the
 * builder says so rather than extrapolating.
 */
export const CREATURE_XP_BY_LEVEL_DIFFERENCE = ${js({
  '-4': 10, '-3': 15, '-2': 20, '-1': 30, 0: 40, 1: 60, 2: 80, 3: 120, 4: 160,
})};
`;
}

// ------------------------------------------------------------------ Conditions

/**
 * The conditions, from the pinned checkout's own condition items rather than
 * from the GM Screen journal: the items carry the full printed text, whether
 * the condition takes a value, and which conditions override which.
 */
function buildConditions(upstream, resolve) {
  const dir = resolvePath(upstream, 'packs/pf2e/conditions');
  const out = {};
  for (const file of readdirSync(dir).filter((f) => f.endsWith('.json'))) {
    const doc = JSON.parse(readFileSync(resolvePath(dir, file), 'utf8'));
    if (doc.type !== 'condition') continue;
    const slug = file.replace(/\.json$/, '');
    const text = resolve(doc.system?.description?.value ?? '', {});
    out[slug] = {
      slug,
      name: doc.name,
      valued: Boolean(doc.system?.value?.isValued),
      group: doc.system?.group ?? null,
      overrides: doc.system?.overrides ?? [],
      source: doc.system?.publication?.title ?? null,
      license: doc.system?.publication?.license ?? null,
      text: text.text,
      html: text.html,
    };
  }

  return header('Conditions.', [
    'From the condition items in the pinned foundryvtt/pf2e checkout, which',
    'carry the printed text, whether a condition takes a value, and which',
    'conditions override which.',
    '',
    'What decreases on its own, and what does not, is not encoded here: it is',
    'in `src/rules/conditions.js`, where each rule cites the sentence it comes',
    'from. Only frightened decreases at the end of a turn; doomed, drained and',
    'fatigued key off a night\'s rest, and stunned off actions actually lost.',
    `Upstream commit ${LOCK.commit}.`,
  ]) + `
export const CONDITIONS = ${js(out)};
`;
}

// ------------------------------------------------------- Creature building

/**
 * The GM Core creature-building tables, transcribed from the book by
 * `tools/build-tables/extract-gm-core.py` and checked in as JSON.
 *
 * This used to be *fitted*: the median of each statistic across the bundled
 * bestiary, because the printed tables are not in any data anyone ships. The
 * medians turned out to track the moderate column closely, which is why it was
 * usable, but it described what Paizo published rather than what the tables
 * prescribe -- and it had one column where the book has four, so a creature
 * with extreme damage scaled at the same rate as a creature with low damage.
 */
function buildCreatureBuilding() {
  const file = resolvePath(PROJECT_ROOT, 'tools/build-tables/gm-core-creature-building.json');
  const raw = JSON.parse(readFileSync(file, 'utf8'));

  // The printed spell table interleaves DC and attack modifier across six
  // columns. The engine wants two tables that each descend from extreme, so
  // that a spell DC can be placed against DC columns and nothing else.
  const { spell, ...rest } = raw;
  const half = (suffix) => ({
    citation: spell.citation,
    columns: ['extreme', 'high', 'moderate'],
    rows: Object.fromEntries(Object.entries(spell.rows).map(([level, cells]) => [
      level,
      spell.columns.flatMap((name, i) => (name.endsWith(suffix) ? [cells[i]] : [])),
    ])),
  });

  const tables = { ...rest, spellDc: half('Dc'), spellAttack: half('Attack') };
  reportAgainstTheBestiary(tables);

  return header('The GM Core creature-building tables.', [
    'Transcribed from the book by `tools/build-tables/extract-gm-core.py`, which',
    'checks every row against the level sequence it must follow and refuses a',
    'printing whose folios do not match the citations below.',
    '',
    'Columns descend: extreme, high, moderate, low, terrible, and each table',
    'carries only the columns the book prints for it. Hit Points and the Skills',
    'low column are printed as ranges and are recorded here as their midpoints,',
    'half rounding up.',
    '',
    'These tables describe how to *build* a creature of a given level. Using',
    'them to move an existing creature between levels is still not rules as',
    'written -- there is no printed operation for that -- but the numbers the',
    'move is built from are now the printed ones. See `src/rules/scale.js`.',
  ]) + `
export const SCALING_SOURCE = 'GM Core pp. 114–121';

export const CREATURE_BUILDING = ${renderTables(tables)};
`;
}

/**
 * One line per level, so a row can be read against the printed page.
 * `js()` would put every cell on a line of its own: 1,600 lines for 9 tables.
 */
function renderTables(tables) {
  const cell = (v) => (v === null ? 'null' : String(v));
  const one = (t) => [
    '{',
    `    citation: '${t.citation}',`,
    `    columns: [${t.columns.map((c) => `'${c}'`).join(', ')}],`,
    '    rows: {',
    // Numeric order, so a row can be found where the book puts it. Object
    // literals reorder integer-like keys at parse time and would bury -1.
    ...Object.entries(t.rows)
      .sort(([a], [b]) => Number(a) - Number(b))
      .map(([level, cells]) => `      '${level}': [${cells.map(cell).join(', ')}],`),
    '    },',
    '  }',
  ].join('\n');
  return `{\n${Object.entries(tables)
    .map(([name, t]) => `  ${name}: ${one(t)},`)
    .join('\n\n')}\n}`;
}

/**
 * Print the printed moderate column beside the bestiary median.
 *
 * Not a check that can fail -- the book is right and the bestiary is a sample --
 * but two independent sources agreeing to within a point or two is how a
 * transcription error announces itself, and it is cheap to look at.
 */
function reportAgainstTheBestiary(tables) {
  const dir = resolvePath(PROJECT_ROOT, 'data/creatures');
  if (!existsSync(dir)) {
    console.log('  data/creatures missing - skipping the sanity check against published creatures.');
    return;
  }

  const median = (values) => {
    if (!values.length) return null;
    const sorted = values.slice().sort((a, b) => a - b);
    const mid = Math.floor(sorted.length / 2);
    return sorted.length % 2 ? sorted[mid] : Math.round((sorted[mid - 1] + sorted[mid]) / 2);
  };

  const buckets = new Map();
  let sampled = 0;
  for (const file of readdirSync(dir).filter((f) => f.endsWith('.json'))) {
    for (const c of JSON.parse(readFileSync(resolvePath(dir, file), 'utf8'))) {
      if (c.supersededBy) continue;              // would double-count its remaster twin
      if (!(String(c.level) in tables.ac.rows)) continue;
      if (!buckets.has(c.level)) buckets.set(c.level, { ac: [], hp: [], save: [] });
      const b = buckets.get(c.level);
      sampled += 1;
      b.ac.push(c.ac.value);
      b.hp.push(c.hp.max);
      for (const key of ['fortitude', 'reflex', 'will']) b.save.push(c.saves[key].mod);
    }
  }

  const moderate = (table, level) => {
    const { columns, rows } = tables[table];
    return rows[String(level)][columns.indexOf('moderate')];
  };

  let worst = { key: null, gap: 0 };
  for (const [level, b] of buckets) {
    for (const key of ['ac', 'save']) {
      const gap = Math.abs(median(b[key]) - moderate(key, level));
      if (gap > worst.gap) worst = { key: `${key} at level ${level}`, gap };
    }
  }
  console.log(
    `  checked against ${sampled} published creatures: the printed moderate column`
    + ` is within ${worst.gap} of the median everywhere (worst: ${worst.key}).`,
  );
}

// ----------------------------------------------------------------------- main

function main() {
  const upstream = ensureUpstream();
  const pages = gmScreenPages(upstream);

  // Condition text contains @UUID links to other conditions, so it goes
  // through the same resolver the creature build uses.
  const { index: uuidIndex } = buildUuidIndex(upstream);
  const glossary = loadGlossary(upstream);
  const { resolve: resolveMarkup } = createMarkupResolver({ uuidIndex, glossary });

  const outputs = [
    ['dcs.js', buildDcTable(pages)],
    ['recall-knowledge.js', buildRecallTable(pages)],
    ['encounter.js', buildEncounterTable(pages)],
    ['conditions.js', buildConditions(upstream, resolveMarkup)],
    ['creature-scaling.js', buildCreatureBuilding()],
  ];

  for (const [name, contents] of outputs) {
    if (contents === null) continue;
    writeFileSync(resolvePath(OUT_DIR, name), contents);
    console.log(`  src/rules/tables/${name}`);
  }
  console.log('Tables written.');
}

main();
