#!/usr/bin/env node
/**
 * `npm run build:tables`
 *
 * Emits the rules engine's lookup tables into `src/rules/tables/` as checked-in
 * ES modules.
 *
 * Checked in rather than generated into `data/` for two reasons: the rules
 * engine must run in the browser with no data build behind it, and the test
 * suite must not depend on `npm run build:data` having been run.
 *
 * Two sources, and the distinction matters:
 *
 *   - The GM Screen journal in the pinned foundryvtt/pf2e checkout. These are
 *     transcriptions of printed GM Core tables and carry a page citation.
 *     Authoritative.
 *   - The normalized bestiary in `data/`. Used only for the level-scaling
 *     table, which has no printed equivalent we can bundle. Fitted, and
 *     labelled as such everywhere it surfaces.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve as resolvePath } from 'node:path';

import { ensureUpstream, LOCK, PROJECT_ROOT } from '../build-data/upstream.js';
import { buildUuidIndex } from '../build-data/uuid-index.js';
import { loadGlossary } from '../build-data/glossary.js';
import { createMarkupResolver } from '../build-data/markup.js';

const OUT_DIR = resolvePath(PROJECT_ROOT, 'src/rules/tables');

/** Minimal `<table>` reader: returns each table as an array of cell-text rows. */
function parseTables(html) {
  const tables = [];
  for (const [, body] of html.matchAll(/<table[^>]*>([\s\S]*?)<\/table>/g)) {
    const rows = [];
    for (const [, tr] of body.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/g)) {
      const cells = [...tr.matchAll(/<t[hd][^>]*>([\s\S]*?)<\/t[hd]>/g)]
        .map(([, c]) => c.replace(/<[^>]+>/g, '').replace(/&[a-z]+;/g, ' ').trim());
      rows.push(cells);
    }
    tables.push(rows);
  }
  return tables;
}

function gmScreenPages(upstream) {
  const file = resolvePath(upstream, 'packs/pf2e/journals/gm-screen.json');
  const journal = JSON.parse(readFileSync(file, 'utf8'));
  const pages = new Map();
  for (const page of journal.pages ?? []) pages.set(page.name, page.text?.content ?? '');
  return pages;
}

/** "Section: Running the Game Pathfinder GM Core pg. 53" -> "GM Core pg. 53". */
function citationOf(html) {
  const m = /Pathfinder\s+(GM Core|Player Core|Monster Core)\s*pg\.\s*(\d+)/.exec(
    html.replace(/<[^>]+>/g, ' '),
  );
  return m ? `${m[1]} pg. ${m[2]}` : null;
}

function header(title, provenance) {
  return `/**\n * ${title}\n *\n${provenance.map((l) => ` * ${l}`).join('\n')}\n *\n * GENERATED by \`npm run build:tables\`. Do not edit by hand.\n */\n`;
}

const js = (v) => JSON.stringify(v, null, 2);

// ---------------------------------------------------------------- DCs by level

function buildDcTable(pages) {
  const html = pages.get('DCs by Level');
  const [levelTable, spellTable] = parseTables(html);

  /** The printed table is two level/DC column pairs side by side. */
  const byLevel = {};
  for (const row of levelTable.slice(1)) {
    const pairs = [[row[0], row[1]], [row[3], row[4]]];
    for (const [lvl, dc] of pairs) {
      if (lvl === undefined || !/^-?\d+$/.test(lvl)) continue;
      byLevel[Number(lvl)] = Number(dc);
    }
  }
  // The bundled table starts at level 0. Level -1 is DC 13 in the printed
  // table, and Recall Knowledge against level -1 creatures is routine, so it
  // is added here rather than left to a clamp.
  byLevel[-1] = 13;

  const bySpellRank = {};
  for (const row of spellTable.slice(1)) {
    const m = /^(\d+)/.exec(row[0] ?? '');
    if (m) bySpellRank[Number(m[1])] = Number(row[1]);
  }

  const adjHtml = pages.get('DC Adjustments');
  const [adjTable] = parseTables(adjHtml);
  const byDifficulty = {};
  const byRarity = {};
  for (const row of adjTable.slice(1)) {
    const [label, adjustment, rarity] = row;
    if (!label || !adjustment) continue;
    const value = Number(adjustment.replace(/[–−]/g, '-').replace(/[^\d-]/g, ''));
    byDifficulty[label.toLowerCase()] = value;
    if (rarity && rarity !== '—' && rarity !== '-') byRarity[rarity.toLowerCase()] = value;
  }
  byRarity.common = 0;

  return header('Level-based DCs and DC adjustments.', [
    `Source: ${citationOf(html) ?? 'GM Core'}, via the pinned pf2e GM Screen journal.`,
    `Upstream commit ${LOCK.commit}.`,
  ]) + `
export const DC_BY_LEVEL = ${js(byLevel)};

export const DC_BY_SPELL_RANK = ${js(bySpellRank)};

/** Difficulty adjustments, e.g. \`hard\` -> +2. */
export const DC_ADJUSTMENT = ${js(byDifficulty)};

/** The rarity each adjustment is tied to, e.g. \`rare\` -> +5. */
export const DC_BY_RARITY = ${js(byRarity)};
`;
}

// -------------------------------------------------------- Recall Knowledge

function buildRecallTable(pages) {
  const html = pages.get('Creature Identification');
  const [table] = parseTables(html);
  const byTrait = {};
  for (const row of table.slice(1)) {
    const [trait, skills] = row;
    if (!trait || !skills) continue;
    byTrait[trait.toLowerCase()] = skills.split(',').map((s) => s.trim().toLowerCase());
  }
  return header('Creature identification: which skill recalls which creature.', [
    `Source: ${citationOf(html) ?? 'GM Core'}, via the pinned pf2e GM Screen journal.`,
    'A creature with no listed trait falls back to Lore, which is always allowed',
    'at the GM’s discretion (GM Core, Recall Knowledge).',
    `Upstream commit ${LOCK.commit}.`,
  ]) + `
export const RK_SKILL_BY_TRAIT = ${js(byTrait)};
`;
}

// ------------------------------------------------------------ Encounter budget

function buildEncounterTable(pages) {
  const html = pages.get('Encounter Budget');
  const [table] = parseTables(html);
  const budget = {};
  for (const row of table.slice(1)) {
    const [difficulty, xp, adjustment] = row;
    if (!difficulty || !xp) continue;
    budget[difficulty.toLowerCase()] = {
      xp: Number(String(xp).replace(/[^\d]/g, '')),
      perCharacter: Number(String(adjustment).replace(/[^\d]/g, '')),
    };
  }
  return header('Encounter budget by difficulty, for a party of four.', [
    `Source: ${citationOf(html) ?? 'GM Core'}, via the pinned pf2e GM Screen journal.`,
    'Creature costs below are the companion table on the same page; they are not',
    'in the bundled journal and are transcribed from the printed table.',
    `Upstream commit ${LOCK.commit}.`,
  ]) + `
export const ENCOUNTER_BUDGET = ${js(budget)};

/**
 * XP a creature costs against the party level, by level difference.
 * GM Core pg. 75. Outside -4..+4 the table simply does not extend, and the
 * builder says so rather than extrapolating.
 */
export const CREATURE_XP_BY_LEVEL_DIFFERENCE = ${js({
  '-4': 10, '-3': 15, '-2': 20, '-1': 30, 0: 40, 1: 60, 2: 80, 3: 120, 4: 160,
})};
`;
}

// ------------------------------------------------------------------ Conditions

/**
 * The conditions, from the pinned checkout's own condition items rather than
 * from the GM Screen journal: the items carry the full printed text, whether
 * the condition takes a value, and which conditions override which.
 */
function buildConditions(upstream, resolve) {
  const dir = resolvePath(upstream, 'packs/pf2e/conditions');
  const out = {};
  for (const file of readdirSync(dir).filter((f) => f.endsWith('.json'))) {
    const doc = JSON.parse(readFileSync(resolvePath(dir, file), 'utf8'));
    if (doc.type !== 'condition') continue;
    const slug = file.replace(/\.json$/, '');
    const text = resolve(doc.system?.description?.value ?? '', {});
    out[slug] = {
      slug,
      name: doc.name,
      valued: Boolean(doc.system?.value?.isValued),
      group: doc.system?.group ?? null,
      overrides: doc.system?.overrides ?? [],
      source: doc.system?.publication?.title ?? null,
      license: doc.system?.publication?.license ?? null,
      text: text.text,
      html: text.html,
    };
  }

  return header('Conditions.', [
    'From the condition items in the pinned foundryvtt/pf2e checkout, which',
    'carry the printed text, whether a condition takes a value, and which',
    'conditions override which.',
    '',
    'What decreases on its own, and what does not, is not encoded here: it is',
    'in `src/rules/conditions.js`, where each rule cites the sentence it comes',
    'from. Only frightened decreases at the end of a turn; doomed, drained and',
    'fatigued key off a night\'s rest, and stunned off actions actually lost.',
    `Upstream commit ${LOCK.commit}.`,
  ]) + `
export const CONDITIONS = ${js(out)};
`;
}

// --------------------------------------------------------- Level scaling (fit)

const SCALE_LEVELS = { min: -1, max: 25 };

function median(values) {
  if (!values.length) return null;
  const sorted = values.slice().sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : Math.round((sorted[mid - 1] + sorted[mid]) / 2);
}

function buildScalingTable() {
  const dir = resolvePath(PROJECT_ROOT, 'data/creatures');
  if (!existsSync(dir)) {
    console.log('  data/creatures missing - run `npm run build:data` first. Scaling table skipped.');
    return null;
  }

  const buckets = new Map();
  let sampled = 0;
  for (const file of readdirSync(dir).filter((f) => f.endsWith('.json'))) {
    for (const c of JSON.parse(readFileSync(resolvePath(dir, file), 'utf8'))) {
      // Superseded legacy reprints would double-count their remaster twin.
      if (c.supersededBy) continue;
      const level = c.level;
      if (level < SCALE_LEVELS.min || level > SCALE_LEVELS.max) continue;
      if (!buckets.has(level)) {
        buckets.set(level, { ac: [], hp: [], perception: [], attack: [], save: [], spellDc: [] });
      }
      const b = buckets.get(level);
      sampled += 1;
      b.ac.push(c.ac.value);
      b.hp.push(c.hp.max);
      b.perception.push(c.perception.mod);
      for (const key of ['fortitude', 'reflex', 'will']) b.save.push(c.saves[key].mod);
      const best = c.strikes.reduce((m, s) => Math.max(m, s.mod), -Infinity);
      if (Number.isFinite(best)) b.attack.push(best);
      for (const entry of c.spellcasting) if (entry.dc) b.spellDc.push(entry.dc);
    }
  }

  const rows = {};
  for (const [level, b] of [...buckets.entries()].sort((a, x) => a[0] - x[0])) {
    rows[level] = {
      n: b.ac.length,
      ac: median(b.ac),
      hp: median(b.hp),
      perception: median(b.perception),
      attack: median(b.attack),
      save: median(b.save),
      spellDc: median(b.spellDc),
    };
  }

  return header('Creature statistics by level, for approximate level scaling.', [
    'NOT rules as written. The GM Core creature-building tables are printed text',
    'and are not present in any bundled data, so this table is fitted: it is the',
    `median of each statistic across ${sampled} bundled creatures, excluding legacy`,
    'reprints superseded by a remaster entry.',
    '',
    'The fit is close to the printed "moderate" column where that can be checked',
    'by hand (level 1 HP 20, level 2 HP 30, level 5 HP 75), which is why it is',
    'usable, but it is a description of what Paizo published rather than of what',
    'the tables prescribe. Scaling built on it must be labelled an approximation',
    'in the interface, distinct from elite and weak.',
    '',
    'To replace it with transcribed GM Core values, overwrite the rows below and',
    'set `source` to a citation; nothing else in the engine needs to change.',
    `Fitted from data built at upstream commit ${LOCK.commit}.`,
  ]) + `
export const SCALING_SOURCE = 'fitted';

export const CREATURE_STATS_BY_LEVEL = ${js(rows)};
`;
}

// ----------------------------------------------------------------------- main

function main() {
  const upstream = ensureUpstream();
  const pages = gmScreenPages(upstream);

  // Condition text contains @UUID links to other conditions, so it goes
  // through the same resolver the creature build uses.
  const { index: uuidIndex } = buildUuidIndex(upstream);
  const glossary = loadGlossary(upstream);
  const { resolve: resolveMarkup } = createMarkupResolver({ uuidIndex, glossary });

  const outputs = [
    ['dcs.js', buildDcTable(pages)],
    ['recall-knowledge.js', buildRecallTable(pages)],
    ['encounter.js', buildEncounterTable(pages)],
    ['conditions.js', buildConditions(upstream, resolveMarkup)],
    ['creature-scaling.js', buildScalingTable()],
  ];

  for (const [name, contents] of outputs) {
    if (contents === null) continue;
    writeFileSync(resolvePath(OUT_DIR, name), contents);
    console.log(`  src/rules/tables/${name}`);
  }
  console.log('Tables written.');
}

main();
